language: java
jdk:
 - openjdk7
 - oraclejdk7
before_deploy: ./bin/build_and_test
deploy:
  provider: heroku
  api_key: 842f09dc-96f9-41e7-bb04-d6360546d5e8
  app : herokutoe
  on:
    app: staging-herokutoe

