/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Homeblest' at '28/10/14 21:45' with Gradle 2.1
 *
 * @author Homeblest, @date 28/10/14 21:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
