/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hjalti' at '10/28/14 10:50 PM' with Gradle 2.1
 *
 * @author hjalti, @date 10/28/14 10:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {

    } 
}
